"""
This type stub file was generated by pyright.
"""

from datetime import date, timedelta
from typing_extensions import Self
from pydantic import field_validator, model_validator
from networth.models.base import NWBase
from networth.models.currency import Currency

class BaseIncomeSource(NWBase):
    amt: Currency
    name: str
    description: str
    ...


class SingletonIncomeSource(BaseIncomeSource):
    income_date: date
    ...


class PeriodicIncomeSource(BaseIncomeSource):
    period: timedelta
    income_start_date: date
    income_end_date: date
    @model_validator(mode="after")
    def validate_dates(self) -> Self:
        ...
    
    def per_month_amt(self) -> Currency:
        ...
    
    def per_year_amt(self) -> Currency:
        ...
    


class ModifiablePeriodicIncomeSource(BaseIncomeSource):
    """A contiguous period of time with a recurring income. The amount may change over time.
    It is not valid to have gaps in time."""
    sources: list[PeriodicIncomeSource]
    @field_validator("sources")
    @classmethod
    def validate_ordered_soruces(cls, sources: list[PeriodicIncomeSource]) -> list[PeriodicIncomeSource]:
        ...
    


